[project]
name = "glossmod-mcp"
version = "0.1.0"
description = "MCP 服务器 - 3DM Mod API 集成"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.18.0",
    "httpx>=0.24.0",
    "pydantic>=2.0.0",
]
